packages:
  - app.*
  - bin.*
  - lib.*
  - svc.*
catalog:
  "@aws-sdk/client-apigatewaymanagementapi": ^3.927.0
  "@aws-sdk/client-dynamodb": ^3.721.0
  "@aws-sdk/client-ssm": ^3.699.0
  "@aws-sdk/lib-dynamodb": ^3.721.0
  "@eslint/js": ^9.39.1
  "@tailwindcss/vite": ^4.1.14
  "@tanstack/react-query": ^5.90.2
  "@tanstack/react-router": ^1.132.33
  "@tanstack/router-plugin": ^1.132.33
  "@types/jsonwebtoken": ^9.0.7
  "@types/node": ^22.12.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@vitejs/plugin-react-swc": ^4.1.0
  aws-cdk: ^2.171.1
  aws-cdk-lib: ^2.171.1
  constructs: ^10.4.2
  esbuild: ^0.24.0
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react-refresh: ^0.4.19
  globals: ^15.15.0
  jsonwebtoken: ^9.0.2
  react: ^19.0.0
  react-dom: ^19.0.0
  react-icons: ^5.5.0
  tailwindcss: ^4.1.14
  ts-node: ^10.9.2
  typescript: ^5.9.3
  typescript-eslint: ^8.24.1
  vite: ^7.1.9
  zod: ^4.1.12
