syntax = "proto3";
import "google/protobuf/descriptor.proto";
import "test.proto";

extend google.protobuf.FieldOptions {
  string validation = 51234;
}
message Pet {
  string name = 1 [(validation) = "required"];
  bool is_cat = 2;
}

message Person {
  message Address {
    string street = 1;
    string city = 2;
    string country = 3;
  }
  message Pet {
    string name = 1;
    bool is_cat = 2;
    bool is_fish = 3;
  }
  string name = 1 [(validation) = "required"];
  int32 age = 2;
  repeated Pet pets = 3;
  Address address = 4;

}


service Greeter {
  rpc SayHello (Person) returns (Person){
    option (network) = true;
  };
}
