syntax = "proto3";
import "google/protobuf/descriptor.proto";


message Config {
  string stage = 1;
  repeated string e = 2;
}
message Table {
  string table = 1;
  string entry = 2;
  string PK = 3;
  string SK = 4;
  repeated string column = 5;
}
extend google.protobuf.FileOptions {
  repeated Config config = 51237;
  repeated Table table = 51239;
}
extend google.protobuf.MethodOptions {
  string api = 51236;
  string using = 51235;
  repeated string secret = 51238;
}
extend google.protobuf.FieldOptions {
  string validation = 51234;
}
message Empty {}
